name: uSkyBlock
main: us.talabrek.ultimateskyblock.uSkyBlock
version: ${project.version}
description: Ultimate SkyBlock v${gitTag}-${buildNumber}-${travis.buildNumber}
author: Talabrek, R4zorax and others
load: STARTUP
depend: [Vault, WorldEdit, WorldGuard]
softdepend: [Multiverse-Core]
commands:
    island:
        description: Commands to use your island
        aliases: [is, skyblock, sb]
        usage:  |
             /island [restart/sethome/info/level/lock/unlock/top/party]
    usb:
        description: admin commands
        aliases: [dev]
        usage:  |
            /usb for more info
    challenges:
        description: skyblock challenges
        aliases: [c, challenge]
        usage:  |  
            /challenges help for more information
permissions:    
  usb.*:
    children:
      usb.island.*:
        children:
          usb.island.create:
            description: Let the player use the /island command
          usb.island.info:
            description: Let the player check their island info(level make-up)
          usb.island.level:
            description: Let the player check their island level
          usb.island.topten:
            description: Let the player see the top ten list
          usb.island.sethome:
            description: Let the player set their island teleport point
          usb.island.challenges:
            description: Let the player use the /challenges command
          usb.island.warp:
            description: Let the player use /island warp to warp to an open island.
          usb.island.ban:
            description: Let the player use /island ban to ban players from warping to their island.
      usb.biome.*:
        children:
          usb.biome.ocean:
            description: Let the player change their islands biome to OCEAN.
          usb.biome.jungle:
            description: Let the player change their islands biome to JUNGLE.
          usb.biome.hell:
            description: Let the player change their islands biome to HELL.
          usb.biome.sky:
            description: Let the player change their islands biome to SKY.
          usb.biome.desert:
            description: Let the player change their islands biome to DESERT.
          usb.biome.forest:
            description: Let the player change their islands biome to FOREST.
          usb.biome.swampland:
            description: Let the player change their islands biome to SWAMPLAND.
          usb.biome.mushroom:
            description: Let the player change their islands biome to MUSHROOM_ISLAND.
          usb.biome.taiga:
            description: Let the player change their islands biome to TAIGA.
          usb.biome.plains:
            description: Let the player change their islands biome to PLAINS.
          usb.biome.extreme_hills:
            description: Let the player change their islands biome to EXTREME_HILLS.
      usb.extra.*:
        children:
          usb.extra.hunger:
            description: The player will lose hunger 25 percent slower.
          usb.extra.hunger2:
            description: The player will lose hunger 50 percent slower.
          usb.extra.hunger3:
            description: The player will lose hunger 75 percent slower.
          usb.extra.hunger4:
            description: The player won't lose hunger on their island.
          usb.extra.partysize:
            description: The player can have 8 total members on their island, which is double the default.
          usb.extra.addwarp:
            description: The player can open his island allowing other players to warp there.
      usb.party.*:
        children:
          usb.party.create:
            description: Let a player invite other players to join a party
          usb.party.kick:
            description: Let a player kick other players
          usb.party.join:
            description: Let a player join another player's party
      usb.mod.*:
        children:
          usb.mod.protect:
            description: Let a player add protection to another player's island
          usb.mod.protectall:
            description: Let a player try to add protection to all unprotected islands
          usb.mod.topten:
            description: Let a player manually update the top ten list
          usb.mod.goto:
            description: Let a player teleport to another player's island
          usb.mod.party:
            description: Let a player access the moderator party commands
          usb.mod.challenges:
            description: Let a player access the moderator challenge commands to complete and reset another player's challenges. 
          usb.mod.bypasscooldowns:
            description: Let a player bypass the cooldowns for the /island info and /island restart commands
          usb.mod.bypassprotection:
            description: Let a player bypass the built in island protection
          usb.mod.bypassteleport:
            description: Let a player bypass the teleport wait time
          usb.mod.setbiome:
            description: Let a player set another players biome.
      usb.admin.*:
        children:
          usb.admin.reload:
            description: Let a player reload the config.yml
          usb.admin.delete:
            description: Let a player completely remove a player's island (including blocks)
          usb.admin.remove:
            description: Let a player remove another player's ownership of an island (island blocks remain)
          usb.admin.register:
            description: Let a player register the nearest island (using the bedrock) to another player.
          usb.admin.bypassspawnprotection:
            description: Let a player bypass the built in spawn protection.
          usb.admin.purge:
            description: Let a player purge old islands.
          usb.admin.import:
            description: Let a player import other-formats (players, islands, orphans).
          usb.admin.topten:
            description: Let a player force top-ten regeneration.
          usb.admin.orphan:
            description: Let a player check and modify the orphan list
